# 每天一个小知识点
## 第四十天 
---

## 输出1
```js
[] == ![] //true
{} == {} //false
{} + [] //0
```
## 输出2
```js
function fn1() {console.log(11)}
function fn2() {console.log(22)}
fn1.call(fn2) // 11
// 多次调用call调用指向了window
fn1.call.call.call.call(fn2) // 22
```
## promise 里面放一个setTimeout的代码块再抛出一个异常,catch是否能捕捉到？
能捕捉到
```js
let promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('reject')
  },0)
}).catch(err=> 
 console.log(err)
)
```
## 性能优化的方法有哪些