# 每天一个小知识点

## 第十九天

---

## 1、事件循环

```js
async function async1() {
  console.log('1');
  await async2();
  console.log('2');
}
async function async2() {
  console.log('3');
}
console.log('4');
setTimeout(function () {
  console.log('5');
  Promise.resolve().then(function () {
    console.log('6');
  });
}, 0);
setTimeout(function () {
  console.log('7');
  Promise.resolve().then(function () {
    console.log('8');
  });
}, 0);
async1();
new Promise(function (resolve) {
  console.log('9');
  resolve();
}).then(function () {
  console.log('10');
});
console.log('11');
```

输出：4、1、3、9、11、2、10、5、6、7、8

## 2、delete

```js
var home = {
  address: 'shanghai',
};
var xrr = Object.create(home);
delete xrr.address;
console.log(xrr.address);
```

输出：shanghai（注意：delete 不能删除原型上的属性）

## 3、运算符、作用域相关

```js
var x = 1;
if (function f() {}) {
  x += typeof f;
}
console.log(x);
```

输出:1undefined(注意：typeof 运算结果为字符串,函数声明写在运算符中，其为 true，但 放在运算符中的函数声明在执行阶段时找不到的)

## 4、闭包

```js
function xrr(n, o) {
  console.log(o);
  return {
    XRR: function (m) {
      return xrr(m, n);
    },
  };
}
const a = xrr(0);
a.XRR(1);
a.XRR(2);
a.XRR(3);
const b = xrr(0).XRR(1).XRR(2).XRR(3);
const c = xrr(0).XRR(1);
c.XRR(2);
c.XRR(3);
// undefined  0 0 0
// undefined  0 1 2
// undefined  0 1 1
```

解析:  
1.a 执行过程：const a = xrr(0); a.XRR(1); a.XRR(2); a.XRR(3)

1> const a = xrr(0); 当把 0 传进去的时候，调用的是外层的函数 xrr 传入参数 0，n 为 0，但是 o 没有值，打印为 undefined，返回一个未执行的函数赋值给 a，其中 a 的 XRR 的 n 为 0  
2> a.XRR(1) ；执行内层的函数 XRR 并传入 1 进去返回执行 xrr 的结果，此时 xrr 传入 1，0 两个参数，打印第二个参数为 0，所以输出为 0  
3> a.XRR(2) ；执行内层的函数 XRR 并传入 1 进去返回执行 xrr 的结果，此时 xrr 传入 2，0 两个参数，打印第二个参数为 0，所以输出为 0  
4> a.XRR(3) ；执行内层的函数 XRR 并传入 1 进去返回执行 xrr 的结果，此时 xrr 传入 3，0 两个参数，打印第二个参数为 0，所以输出为 0  
所以结果是 undefined 0 0 0

2.b 执行过程：const b = xrr(0).XRR(1).XRR(2).XRR(3)

1> 第一次调用第一层 xrr(0) 时，o 为 undefined  
2> 第二次调用 .XRR(1) 时 m 为 1，此时 xrr 闭包了外层函数的 n ，也就是第一次调用的 n=0，即 m=1,n=0，并在内部调用第一层的 xrr(1,0)；所以 o 为 0  
3> 第三次调用 .XRR(2) 时 m 为 2，此时当前的 xrr 函数不是第一次执行的返回对象，而是第二次执行的返回对象。而在第二次第一层 xrr(1,0) 时，n=1,o=0，返回时闭包了第二次的 n，所以在第三次调用第三层的 XRR 函数时，m=2,n=1，即调用第一层 xrr（2，1） 函数，所以 o 为 1  
4> 第四次调用 .XRR(3) 时 m=3，闭包了第三次的 n ，同理，最终调用第一层 xrr(3,2)；所以 o 为 2

所以结果为： undefined 0 1 2

3.c 执行过程：const c = xrr(0).XRR(1); c.XRR(2); c.XRR(3)

1> const c = xrr(0)：调用第一层 xrr(0) 时，o 为 undefined  
2> 第二次调用 .XRR(1) 时 m 为 1，此时 XRR 闭包了外层函数的 n ，也就是第一次调用的 n=0，即 m=1,n=0，并在内部调用第一层的 xrr(1,0)；所以 o 为 0  
3> 第三次调用 .XRR(2) 时 m 为 2，此时 xrr 闭包的是第二次执行的返回的函数 XRR（内层的 xrr(m=2(本次传入的 2),n=1（私有值 1）),所以外层的 xrr(n=2,o=1)）。所以打印 o 输出为 1  
4> 第四次 .XRR(3) 时同理，但依然时调用第二次的返回值，所以最终调用第一层的 XRR(3,1)，所以 o 为 1

所以结果是 undefined 0 1 1
